print ("                    TOKO SEMBAKO                 ")
print ("                 ******************              ")
Nama_Pembeli = (input ( "Nama Pembeli :" ))
Kode = (input ("Kode Sembako :"))
Harga = (input ("harga :"))
Pembelian = (input ("jumlah pembelian :"))
print ("==================================")
print ("Nama Pembeli")
print ("Kode Sembako")
print ("Harga")
print ("pembelian")
ngka=int(input('nilai a:'))
